node_json: example/node.json
secrets:
  - alice
consul_lock_limit: 1
loggers:
  - type: stdout
  - type: file
    path: /tmp/itamae-client.log
  - type: syslog
  - type: cloud_watch_logs
    log_group: itamae-client-example
